name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ 4990f711-14d0-4fe4-903a-97b2bff0e692 }}
          GH_TOKEN: ${{ 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 }}
